# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-29 20:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_todo_hecho'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='hecho',
            field=models.BooleanField(default=False),
        ),
    ]
